### ISSUE TITLE
Invalid type (maybe invalid usage)

### ISSUE THREAD

**Issue by acepace** [UselessPickles/ts-enum-util#14]
I have the following code

```
export enum DecisionType {
  DECISION = 'whatever,
  UNDEFINED = 'undef'
}
```

And I want to make sure I receive a string that is one of the legal value and return the correct key.
If I understand correctly, I should be doing this
```
export function DecisionTypeString (decisionStr: string): StringKeyOf<DecisionType> {
  let value = $enum(DecisionType).asValueOrDefault(decisionStr, DecisionType.UNDEFINED)
  let retval =  $enum(DecisionType).getKeyOrDefault(value, DecisionType.UNDEFINED)
  return retval
}
```

However, I get the following error message
```
CaseEnums.ts:15:3 - error TS2322: Type 'string' is not assignable to type '"toString" | "charAt" | "charCodeAt" | "concat" | "indexOf" | "lastIndexOf" | "localeCompare" | "match" | "replace" | "search" | "slice" | "split" | "substring" | "toLowerCase" | ... 29 more ... | "trimRight"'.
```

What am I doing wrong?

**Comment by UselessPickles** [comment]
Part of the problem is that the return type of your function is incorrect: `StringKeyOf<DecisionType>`

The type `DecisionType` is similar to a string literal union of all the possible enum values. So `StringKeyOf<DecisionType>` is effectively the same as `StringKeyOf<string>`, which gives you the names of all functions available on `string`.

To get a type that is all string literal union of all names in an enum, you need `StringKeyOf<typeof DecisionType>`. In this expression, `DecisionType` is referring to the run-time value that is the object containing all of the enum keys/values.

Your next problem is the default key you provide to `getKeyOrDefault()` is an enum value; not a key. Because you didn't provide a valid key as the default value, the return type of that call is broadened to `string`. This is probably what you meant to do: 
```
let retval =  $enum(DecisionType).getKeyOrDefault(value, "UNDEFINED")
```
